#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <utility>

#include <Orbitals/Orbitals.h>
#include <Utils/LM.h>


void Orbitals::Save(const std::string& tag)
{
    if(tag.find(".wfx")!=std::string::npos)
        Save_wfx(tag);
    else if(tag.find(".molden")!=std::string::npos)
        Save_molden(tag);
    else if(tag.find(".gab")!=std::string::npos)
        Save_gab(tag);
    else
    {
        std::cout<<"Format not recognize, please choose a valide format"<<std::endl;
        std::exit(1);
    }
}

void Orbitals::Save_wfx(const std::string& tag)
{
    int n, nMO;
    std::ofstream s;
    s.open(tag);

    s<<"<Title>"<<std::endl;
    s<<" Input file generated by cdftt..."<<std::endl;
    s<<"</Title>"<<std::endl;

    s<<"<Keywords>"<<std::endl;
    s<<" GTO"<<std::endl;
    s<<"</Keywords>"<<std::endl;

    s<<"<Number of Nuclei>"<<std::endl;
    s<<" "<<_numberOfAtoms<<std::endl;
    s<<"</Number of Nuclei>"<<std::endl;

    s<<"<Number of Occupied Molecular Orbitals>"<<std::endl;
    if(!_alphaAndBeta)
        nMO=_numberOfMo*2;
    else
        nMO=_numberOfMo;
    s<<" "<<nMO<<std::endl;
    s<<"</Number of Occupied Molecular Orbitals>"<<std::endl;

    s<<"<Number of Perturbations>"<<std::endl;
    s<<" 0"<<std::endl;
    s<<"</Number of Perturbations>"<<std::endl;

    s<<"<Net Charge>"<<std::endl;
    s<<" 0"<<std::endl;
    s<<"</Net Charge>"<<std::endl;

    s<<"<Number of Electrons>"<<std::endl;
    s<<" "<<_numberOfAlphaElectrons+_numberOfBetaElectrons<<std::endl;
    s<<"</Number of Electrons>"<<std::endl;

    s<<"<Number of Alpha Electrons>"<<std::endl;
    s<<" "<<_numberOfAlphaElectrons<<std::endl;
    s<<"</Number of Alpha Electrons>"<<std::endl;

    s<<"<Number of Beta Electrons>"<<std::endl;
    s<<" "<<_numberOfBetaElectrons<<std::endl;
    s<<"</Number of Beta Electrons>"<<std::endl;

    s<<"<Nuclear Names>"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
        s<<" "<<_symbol[i]<<i+1<<std::endl;
    s<<"</Nuclear Names>"<<std::endl;

    s<<"<Atomic Numbers>"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
        s<<" "<<_atomicNumbers[i]<<std::endl;
    s<<"</Atomic Numbers>"<<std::endl;    

    s<<"<Nuclear Charges>"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
        s<<std::right<<std::scientific<<std::setprecision(12)<<" "<<std::setw(20)<<double(_atomicNumbers[i])<<std::endl;
    s<<"</Nuclear Charges>"<<std::endl;

    s<<"<Nuclear Cartesian Coordinates>"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
    {
        for(int j=i*3; j<(i+1)*3; j++)
            s<<std::right<<std::scientific<<std::setprecision(12)<<" "<<std::setw(20)<<_coordinates[j];
        s<<std::endl;
    }
    s<<"</Nuclear Cartesian Coordinates>"<<std::endl;

    s<<"<Number of Primitives>"<<std::endl;
    s<<" "<<_numberOfGtf<<std::endl;
    s<<"</Number of Primitives>"<<std::endl;

    s<<"<Primitive Centers>"<<std::endl;

    if(int(_vcgtfUnnormalized.size())==_numberOfGtf)
        for(int i=0; i<_numberOfGtf; i++)
        {
            s<<"\t"<<_primitiveCenters[i];
            if((i+1)%5==0)
                s<<std::endl;
        }
    else
    {
        std::vector<int> pc;
        for(size_t i=0; i<_vcgtf.size(); i++)
            for(int j=0; j<_vcgtf[i].numberOfFunctions(); j++)
                pc.push_back(_vcgtf[i].NumCenter());

        for(int i=0; i<_numberOfGtf; i++)
        {
            s<<"\t"<<pc[i];
            if((i+1)%5==0)
                s<<std::endl;
        }
    }
    s<<std::endl;
    s<<"</Primitive Centers>"<<std::endl;

    n=0;
    s<<"<Primitive Types>"<<std::endl;
    for(size_t i=0; i<_vcgtf.size(); i++)
        for(int j=0; j<_vcgtf[i].numberOfFunctions(); j++)
        {
            s<<"\t"<<getwfxType(_vcgtf[i].gtf()[j].get_l());
            if((n+1)%5==0)
                s<<std::endl;
            n++;
        }
    s<<std::endl;
    s<<"</Primitive Types>"<<std::endl;

    n=0;
    s<<"<Primitive Exponents>"<<std::endl;
    for(size_t i=0; i<_vcgtf.size(); i++)
        for(int j=0; j<_vcgtf[i].numberOfFunctions(); j++)
        {
            s<<std::right<<std::scientific<<std::setprecision(12)<<"\t"<<std::setw(20)<<_vcgtf[i].gtf()[j].get_exponent();
            if((n+1)%5==0)
                s<<std::endl;
            n++;
        }
    s<<std::endl;
    s<<"</Primitive Exponents>"<<std::endl;

    int m;

    if(_alphaAndBeta)
        m=1;
    else
        m=2;

    s<<"<Molecular Orbital Occupation Numbers>"<<std::endl;
    for(int i=0; i<m; i++)
        for(int j=0; j<_numberOfMo; j++)
            s<<" "<<_occupationNumber[i][j]<<std::endl;
    s<<"</Molecular Orbital Occupation Numbers>"<<std::endl;

    s<<"<Molecular Orbital Energies>"<<std::endl;
    for(int i=0; i<m; i++)
        for(size_t j=0; j<_orbitalEnergy[i].size(); j++)
            s<<std::right<<std::scientific<<std::setprecision(12)<<" "<<std::setw(20)<<_orbitalEnergy[i][j]<<std::endl;
    s<<"</Molecular Orbital Energies>"<<std::endl;

    s<<"<Molecular Orbital Spin Types>"<<std::endl;
    if(m==1)
        for(int i=0; i<_numberOfMo; i++)
            s<<" "<<"Alpha and Beta"<<std::endl;
    else
    {
        for(size_t i=0; i<_orbitalEnergy[0].size(); i++)
            s<<" "<<"Alpha"<<std::endl;
        for(size_t i=0; i<_orbitalEnergy[1].size(); i++)
            s<<" "<<"Beta"<<std::endl;
    }
    s<<"</Molecular Orbital Spin Types>"<<std::endl;

    s<<"<Molecular Orbital Primitive Coefficients>"<<std::endl;
    int a=0,b=0;
    for(int i=0; i<m; i++)
        for(int j=0; j<_numberOfMo; j++)
        {
            a++;
            s<<"<MO Number>"<<std::endl;
            s<<" "<<a<<std::endl;
            s<<"</MO Number>"<<std::endl;
        
            for(size_t k=0; k<_vcgtf.size(); k++)
                for(int l=0; l<_vcgtf[k].numberOfFunctions(); l++)
                {
                    s<<std::right<<std::scientific<<std::setprecision(12)<<" "<<std::setw(20)<<_vcgtf[k].coefficients()[l]*_vcgtf[k].gtf()[l].get_coefficient()*_coefficients[i][j][k];

                    if((b+1)%4==0)
                        s<<std::endl;
                    b++;
                }

            if(b%4!=0)
                s<<std::endl;
        }
    s<<"</Molecular Orbital Primitive Coefficients>"<<std::endl;

    s<<"<Energy = T + Vne + Vee + Vnn>"<<std::endl;
    s<<" "<<_energy<<std::endl;
    s<<"</Energy = T + Vne + Vee + Vnn>"<<std::endl;

    s<<"<Virial Ratio (-V/T)>"<<std::endl;
    s<<" "<<std::scientific<<std::setprecision(12)<<2<<std::endl;
    s<<"</Virial Ratio (-V/T)>"<<std::endl;

    s.close();
}
                                                            // Moldengab faire attention au format sphe/cart !!!!
void Orbitals::Save_molden(const std::string& tag)    
{
    // ? _vcgtfUnnormalized : vector of Contracted Gaussian Type Functions (CGTF) that compose the basis set without normalization
    // ? _numberOfGtf : Number of primitive functions
    //      -> only `.wfx` or other primitive-only formats should trigger this condition
    if(int(_vcgtfUnnormalized.size())==_numberOfGtf)
    {
        /* Reminder : how are orbitals computed in most formats (e.g. Molden, Gabedit)
            
            A given shell is built from a set of primitive functions, usually Gaussian Type Functions
            (GTFs).
                {g_1, g_2, ..., g_n}
            
            One then builds a contracted basis function (CBF) by taking a linear combination of these
            primitives:
                CBF = c_1 * g_1 + c_2 * g_2 + ... + c_n * g_n

            Afterwards, one performs a simple expansion (ie. another linear combination) of the
            molecular orbitals (MOs) in terms of these contracted basis functions:
                MO = C_1 * CBF_1 + C_2 * CBF_2 + ... + C_m * CBF_m
            
            Or, if we replace CBFs in the previous equation
                MO = (C_1 * c_1) * g_1 + (C_1 * c_2) * g_2 + ... + (C_1 * c_n) * g_n
                   + (C_2 * c_1) * g_1 + (C_2 * c_2) * g_2 + ... + (C_2 * c_n) * g_n
                   + ... 
                   + (C_m * c_1) * g_1 + (C_m * c_2) * g_2 + ... + (C_m * c_n) * g_n    ----    [CASE 1]

        For the .wfx format, the process is a bit different:
        
            Starting from the same set of primitive functions,
                {g_1, g_2, ..., g_n}

            one can directly expand the molecular orbitals in terms of these primitives, skipping the
            intermediate contracted basis functions:
                MO = D_1 * g_1 + D_2 * g_2 + ... + D_n * g_n    ----   [CASE 2]

            Therefore, instead of explicitely performing the contraction and then the expansion like in
            [CASE 1], the contraction is absorbed into the D_* coefficients of the primitive functions
            in [CASE 2].

        Therefore, critical differences appear in storage :
            - in [CASE 1],
                one can store for each shell information regarding the first linear combination (in the
                [GTO] section for .molden)
                    {a_i, c_i} where a_i define the exponents of the primitives and c_i are the
                    contraction coefficients
                and then store the second linear combination (in the [MO] section for .molden)
                    {C_i} where C_i are the expansion coefficients of the MOs in terms of the
                    contracted basis functions
            - in [CASE 2],
                one can only store the expansion coefficients of the MOs in terms of the primitives,
                which are the D_i coefficients in the previous equation. The contraction coefficients
                c_i are not stored anywhere, and therefore the contracted basis functions are not
                explicitly defined in the `.wfx` format.

            In other words, the `.wfx` format is a "primitive-only" format (explaining why we check if
            the number of primitives is equal to the number of contracted basis functions in the `if`
            statement above).

        The conversion from [CASE 2] to [CASE 1] is not implemented yet as the reconstruction of the
        contracted basis functions from the primitive-only expansion is not unique.

        We would have to choose a convention. The easiest one would be to assume that
            "one primitive function" = "one contracted basis function"
        but I am unsure of whether this is a good idea and what are the edge cases.
        */
        std::cout<<"Conversion to Molden format from .wfx is not implemented yet."<<std::endl;
        // ! Triggered by .wfx to .molden conversion
        return;
    }

    std::ofstream s;
    s.open(tag);

    s<<"[Molden Format]"<<std::endl;

    s<<"[Atoms] AU"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
    {
        s<<_symbol[i]<<" "<<i+1<<" "<<_atomicNumbers[i];
        for(int j=i*3; j<(i+1)*3; j++)
            s<<std::fixed<<std::setprecision(6)<<std::right<<"  "<<std::setw(10)<<_coordinates[j];
        s<<std::endl;
    }

    s<<std::endl;
    
    bool d=false, f=false, g=false;

    for(size_t i=0; i<_vcgtfUnnormalized.size(); i++)
    {
        if(_vcgtfUnnormalized[i].Lformat()=="Sphe")
        {
            if((_vcgtfUnnormalized[i].Ltype()=="D" || _vcgtfUnnormalized[i].Ltype()=="d") && !d)
            {
                s<<"[5D] ";
                d=true;
            }
            else if((_vcgtfUnnormalized[i].Ltype()=="F" || _vcgtfUnnormalized[i].Ltype()=="f") &&!f)
            {
                s<<"[7F] ";
                f=true;
            }
            else if((_vcgtfUnnormalized[i].Ltype()=="G" || _vcgtfUnnormalized[i].Ltype()=="d") && !g)
            {
                s<<"[9G] ";
                g=true;
            }
        }
    }

    s<<std::endl<<"[GTO]"<<std::endl;

    int lt,q,m,k=0;
    double save_alpha;

    for(int i=0; i<_numberOfAtoms; i++)
    {
        s<<"\t"<<_vcgtfUnnormalized[k].NumCenter()<<" "<<0<<std::endl;

        do{
            if(k==0)    //First shell
            {
                s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                    s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                k++;
            }

            else if(k+1<int(_vcgtfUnnormalized.size()))    //Other shell
            {
                if(_vcgtfUnnormalized[k].Ltype()==_vcgtfUnnormalized[k+1].Ltype() && _vcgtfUnnormalized[k].gtf()[0].get_exponent()==_vcgtfUnnormalized[k+1].gtf()[0].get_exponent())    //Other format
                {
                    lt=_vcgtfUnnormalized[k].gtf()[0].get_l()[0]+_vcgtfUnnormalized[k].gtf()[0].get_l()[1]+_vcgtfUnnormalized[k].gtf()[0].get_l()[2];

                    if(_vcgtfUnnormalized[k].Lformat()=="Cart")
                        m=(lt+1)*(lt+2)/2;
                    else
                        m=2*lt+1;

                    s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                    s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                    for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                        s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                    k+=m;
                }

                else if(_vcgtfUnnormalized[k].Ltype()==_vcgtfUnnormalized[k+1].Ltype())           //WFX
                {
                    lt=_vcgtfUnnormalized[k].gtf()[0].get_l()[0]+_vcgtfUnnormalized[k].gtf()[0].get_l()[1]+_vcgtfUnnormalized[k].gtf()[0].get_l()[2];

                    if(lt!=0)
                    {
                        m=(lt+1)*(lt+2)/2;
                        q=k;
                        save_alpha=_vcgtfUnnormalized[k].gtf()[0].get_exponent();

                        do{
                            s<<" "<<_vcgtfUnnormalized[q].Ltype()<<"\t"<<_vcgtfUnnormalized[q].numberOfFunctions()<<"  ";
                            s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[q].FactorCoef()<<std::endl;

                            for(int j=0; j<_vcgtfUnnormalized[q].numberOfFunctions(); j++)
                                s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[q].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[q].coefficients()[j]<<std::endl;

                            q++;
                        }while(q+1<int(_vcgtfUnnormalized.size()) && _vcgtfUnnormalized[q].gtf()[0].get_exponent()!=save_alpha);
                        //q=q-k+1;        don't work for h2otest.wfx
                        q=q-k;
                        //k+=q*(m-1)+1;      don't work for h2otest.wfx
                        k+=q*m;
                    }

                    else
                    {
                        s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                        s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                        for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                            s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                        k++;
                    }
                }

                else               //Other case
                {
                    s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                    s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                    for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                        s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                    k++;
                }
            }
            else               //Last shell
            {
                s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                    s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                k++;
            }
        }while(k<int(_vcgtfUnnormalized.size()) && i+1==_vcgtfUnnormalized[k].NumCenter());
        s<<std::endl;
    }

    s<<std::endl;

    s<<"[MO]"<<std::endl;

    int n;
    if(_alphaAndBeta)
        n=2;
    else
        n=1;

    for(int i=0; i<2; i++)
        for(size_t j=0; j<_coefficients[i].size(); j++)
        {
            s<<std::setprecision(6)<<" Ene= "<<_orbitalEnergy[i][j]<<std::endl;
            if(i==0)
                s<<" Spin= Alpha"<<std::endl;
            else
                s<<" Spin= Beta"<<std::endl;
            s<<std::setprecision(6)<<" Occup= "<<_occupationNumber[i][j]/double(n)<<std::endl;
            s<<" Sym= unk"<<std::endl;

            for(size_t k=0; k<_coefficients[i][j].size(); k++)
            {
                s<<"\t"<<" "<<k+1<<"\t"<<"\t";
                s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(15)<<_coefficients[i][j][k]<<std::endl;
            }
        }

    s<<std::endl;
    s<<"[AO]"<<std::endl;
    s<<std::endl;

    s.close();
}

void Orbitals::Save_gab(const std::string& tag)
{
    if(_mixte)
    {
        std::cout<<"Gabedit format can't handle mixed cartesian and spherical harmonic basis." <<std::endl;
        // ! Triggered by .molden to .gab conversion
        return;
    }

    // ? _vcgtfUnnormalized : vector of Contracted Gaussian Type Functions (CGTF) that compose the basis set without normalization
    // ? _numberOfGtf : Number of primitive functions
    //      -> only `.wfx` or other primitive-only formats should trigger this condition
    if(int(_vcgtfUnnormalized.size())==_numberOfGtf)
    {
        /* Reminder : how are orbitals computed in most formats (e.g. Molden, Gabedit)
            
            A given shell is built from a set of primitive functions, usually Gaussian Type Functions
            (GTFs).
                {g_1, g_2, ..., g_n}
            
            One then builds a contracted basis function (CBF) by taking a linear combination of these
            primitives:
                CBF = c_1 * g_1 + c_2 * g_2 + ... + c_n * g_n

            Afterwards, one performs a simple expansion (ie. another linear combination) of the
            molecular orbitals (MOs) in terms of these contracted basis functions:
                MO = C_1 * CBF_1 + C_2 * CBF_2 + ... + C_m * CBF_m
            
            Or, if we replace CBFs in the previous equation
                MO = (C_1 * c_1) * g_1 + (C_1 * c_2) * g_2 + ... + (C_1 * c_n) * g_n
                   + (C_2 * c_1) * g_1 + (C_2 * c_2) * g_2 + ... + (C_2 * c_n) * g_n
                   + ... 
                   + (C_m * c_1) * g_1 + (C_m * c_2) * g_2 + ... + (C_m * c_n) * g_n    ----    [CASE 1]

        For the .wfx format, the process is a bit different:
        
            Starting from the same set of primitive functions,
                {g_1, g_2, ..., g_n}

            one can directly expand the molecular orbitals in terms of these primitives, skipping the
            intermediate contracted basis functions:
                MO = D_1 * g_1 + D_2 * g_2 + ... + D_n * g_n    ----   [CASE 2]

            Therefore, instead of explicitely performing the contraction and then the expansion like in
            [CASE 1], the contraction is absorbed into the D_* coefficients of the primitive functions
            in [CASE 2].

        Therefore, critical differences appear in storage :
            - in [CASE 1],
                one can store for each shell information regarding the first linear combination (in the
                [GTO] section for .molden)
                    {a_i, c_i} where a_i define the exponents of the primitives and c_i are the
                    contraction coefficients
                and then store the second linear combination (in the [MO] section for .molden)
                    {C_i} where C_i are the expansion coefficients of the MOs in terms of the
                    contracted basis functions
            - in [CASE 2],
                one can only store the expansion coefficients of the MOs in terms of the primitives,
                which are the D_i coefficients in the previous equation. The contraction coefficients
                c_i are not stored anywhere, and therefore the contracted basis functions are not
                explicitly defined in the `.wfx` format.

            In other words, the `.wfx` format is a "primitive-only" format (explaining why we check if
            the number of primitives is equal to the number of contracted basis functions in the `if`
            statement above).

        The conversion from [CASE 2] to [CASE 1] is not implemented yet as the reconstruction of the
        contracted basis functions from the primitive-only expansion is not unique.

        We would have to choose a convention. The easiest one would be to assume that
            "one primitive function" = "one contracted basis function"
        but I am unsure of whether this is a good idea and what are the edge cases.
        */
        std::cout<<"Conversion to Gabedit format from .wfx is not implemented yet."<<std::endl;
        // ! Triggered by .wfx to .molden conversion
    }

    std::ofstream s;
    s.open(tag);

    s<<"[Gabedit Format] Cart"<<std::endl;

    s<<"[Atoms] AU"<<std::endl;
    for(int i=0; i<_numberOfAtoms; i++)
    {
        s<<_symbol[i]<<" "<<i+1<<" "<<_atomicNumbers[i];
        for(int j=i*3; j<(i+1)*3; j++)
            s<<std::fixed<<std::setprecision(6)<<std::right<<"  "<<std::setw(10)<<_coordinates[j];
        s<<std::endl;
    }

    s<<"[Basis]"<<std::endl;

    int lt,q,m,k=0;
    double save_alpha;

    for(int i=0; i<_numberOfAtoms; i++)
    {
        s<<"\t"<<_vcgtfUnnormalized[k].NumCenter()<<" "<<0<<std::endl;

        do{
            if(k==0)    //First shell
            {
                s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                    s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                k++;
            }

            else if(k+1<int(_vcgtfUnnormalized.size()))    //Other shell
            {
                if(_vcgtfUnnormalized[k].Ltype()==_vcgtfUnnormalized[k+1].Ltype() && _vcgtfUnnormalized[k].gtf()[0].get_exponent()==_vcgtfUnnormalized[k+1].gtf()[0].get_exponent())    //Other format
                {
                    lt=_vcgtfUnnormalized[k].gtf()[0].get_l()[0]+_vcgtfUnnormalized[k].gtf()[0].get_l()[1]+_vcgtfUnnormalized[k].gtf()[0].get_l()[2];

                    if(_vcgtfUnnormalized[k].Lformat()=="Cart")
                        m=(lt+1)*(lt+2)/2;
                    else
                        m=2*lt+1;

                    s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                    s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                    for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                        s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                    k+=m;
                }

                else if(_vcgtfUnnormalized[k].Ltype()==_vcgtfUnnormalized[k+1].Ltype())           //WFX
                {
                    lt=_vcgtfUnnormalized[k].gtf()[0].get_l()[0]+_vcgtfUnnormalized[k].gtf()[0].get_l()[1]+_vcgtfUnnormalized[k].gtf()[0].get_l()[2];

                    if(lt!=0)
                    {
                        m=(lt+1)*(lt+2)/2;
                        q=k;
                        save_alpha=_vcgtfUnnormalized[k].gtf()[0].get_exponent();

                        do{
                            s<<" "<<_vcgtfUnnormalized[q].Ltype()<<"\t"<<_vcgtfUnnormalized[q].numberOfFunctions()<<"  ";
                            s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[q].FactorCoef()<<std::endl;

                            for(int j=0; j<_vcgtfUnnormalized[q].numberOfFunctions(); j++)
                                s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[q].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[q].coefficients()[j]<<std::endl;

                            q++;
                        }while(q+1<int(_vcgtfUnnormalized.size()) && _vcgtfUnnormalized[q].gtf()[0].get_exponent()!=save_alpha);
                        //q=q-k+1;        don't work for h2otest.wfx
                        q=q-k;
                        //k+=q*(m-1)+1;      don't work for h2otest.wfx
                        k+=q*m;
                    }

                    else
                    {
                        s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                        s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                        for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                            s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                        k++;
                    }
                }

                else               //Other case
                {
                    s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                    s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                    for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                        s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                    k++;
                }
            }
            else               //Last shell
            {
                s<<" "<<_vcgtfUnnormalized[k].Ltype()<<"\t"<<_vcgtfUnnormalized[k].numberOfFunctions()<<"  ";
                s<<std::fixed<<std::setprecision(1)<<_vcgtfUnnormalized[k].FactorCoef()<<std::endl;

                for(int j=0; j<_vcgtfUnnormalized[k].numberOfFunctions(); j++)
                    s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(6)<<" "<<std::setw(15)<<_vcgtfUnnormalized[k].gtf()[j].get_exponent()<<"  "<<std::setw(15)<<_vcgtfUnnormalized[k].coefficients()[j]<<std::endl;

                k++;
            }
        }while(k<int(_vcgtfUnnormalized.size()) && i+1==_vcgtfUnnormalized[k].NumCenter());
        s<<std::endl;
    }

    s<<std::endl;

    s<<"[MO]"<<std::endl;

    int n;
    if(_alphaAndBeta)
        n=2;
    else
        n=1;

    for(int i=0; i<2; i++)
        for(size_t j=0; j<_coefficients[i].size(); j++)
        {
            s<<std::setprecision(6)<<" Ene= "<<_orbitalEnergy[i][j]<<std::endl;
            if(i==0)
                s<<" Spin= Alpha"<<std::endl;
            else
                s<<" Spin= Beta"<<std::endl;
            s<<std::setprecision(6)<<" Occup= "<<_occupationNumber[i][j]/double(n)<<std::endl;
            s<<" Sym= unk"<<std::endl;

            for(size_t k=0; k<_coefficients[i][j].size(); k++)
            {
                s<<"\t"<<" "<<k+1<<"\t"<<"\t";
                s<<std::fixed<<std::setprecision(6)<<std::right<<std::setw(15)<<_coefficients[i][j][k]<<std::endl;
            }
        }

    s<<std::endl;
    s<<"[AO]"<<std::endl;
    s<<std::endl;

    s.close();
}

void Orbitals::Sorting()
{
    int k=0,q=0,pos,lt,m=0;

    if(_numberOfGtf==int(_vcgtf.size()))
    {
        for(int i=0; i<_numberOfAtoms; i++)
        {
            do{
                if(k+1<int(_vcgtf.size()))
                {
                    if((_vcgtf[k].Ltype()=="s" || _vcgtf[k].Ltype()=="S") || (_vcgtf[k+1].Ltype()=="s" || _vcgtf[k+1].Ltype()=="S"))
                        q=0;

                    else if(_vcgtf[k].Ltype()==_vcgtf[k+1].Ltype())
                    {
                        lt=_vcgtf[k].gtf()[0].get_l()[0]+_vcgtf[k].gtf()[0].get_l()[1]+_vcgtf[k].gtf()[0].get_l()[2];
                        m=(lt+1)*(lt+2)/2;
                        q=k;

                        do{
                            q++;
                        }while(_vcgtf[q].Ltype()==_vcgtf[k].Ltype());

                        q=q-k;
                        k+=q+1;
                    }

                    if(q>m)
                    {
                        pos=k-q-1;
                        q=pos;

                        for(int ind=0; ind<m-1; ind++)
                        {
                            q++;
                            std::swap(_vcgtf[q], _vcgtf[q+m-1]);
                            q+=m;
                        }

                        q=pos+m-1;

                        std::swap(_vcgtf[q], _vcgtf[q+m+1]);

                        q=0;
                        k++;
                    }

                    else
                    {
                        k++;
                        continue;
                    }
                }
                else
                {
                    k++;
                    continue;
                }
            }while(k<int(_vcgtf.size()) && i+1==_vcgtf[k].NumCenter());
        }
        DenormaliseAllBasis();
    }
}
